"""add fk business_settings business_id

Revision ID: 4b730f2849c9
Revises: 0206199836ec
Create Date: 2026-07-24 21:09:02.601808

"""
from alembic import op
import sqlalchemy as sa


revision = '4b730f2849c9'
down_revision = '0206199836ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'business_settings', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_settings', type_='foreignkey')
    # ### end Alembic commands ###
